function Scene(){typeof Float64Array!=="undefined"&&(glMatrixArrayType=Float64Array);this.initialTime=(new Date).getTime();typeof FlashCanvas!="undefined"&&(FlashCanvas.initElement($("#canvas")[0]),FlashCanvas.initElement($("#minkowski")[0]),FlashCanvas.initElement($("#3DCanvas")[0]));this.g=$("#canvas")[0].getContext("2d");this.h=$("#minkowski")[0].getContext("2d");this.TDC=$("#3DCanvas")[0].getContext("2d");this.g.font="0.8em Helvetiker, helvetica, arial, sans-serif";this.h.font="0.8em Helvetiker, helvetica, arial, sans-serif";
this.loaded=false;this.TDC.font="0.8em Helvetiker, helvetica, arial, sans-serif";this.width=$("#canvas").width();this.height=$("#canvas").height();this.mWidth=$("#minkowski").width();this.mHeight=$("#minkowski").height();this.tWidth=$("#3DCanvas").width();this.tHeight=$("#3DCanvas").height();this.lightConeCanvas=document.createElement("canvas");this.lightConeCanvas.width=this.mWidth;this.lightConeCanvas.height=this.mHeight;typeof FlashCanvas!="undefined"&&FlashCanvas.initElement(this.lightConeCanvas);
this.lCCtx=this.lightConeCanvas.getContext("2d");this.lCCtx.font="0.8em Helvetiker, helvetica, arial, sans-serif";if(!this.TDC.fillText)this.TDC.fillText=function(){},this.g.fillText=function(){},this.h.fillText=function(){};this.camBack=this.kC=0;this.hwidth=this.width/2;this.hheight=this.height/2;this.origin=[this.hwidth,this.hheight,this.hheight];this.carray=[];this.timeZoom=this.zoom=0.25;this.t=0;this.keyDown=false;this.defaults={showDoppler:true,showVisualPos:true,showFramePos:false,showVelocity:true,
showTime:false,showGamma:true,show3D:false,showPos:false,c:3,showText:true,timeScale:0.01,showMinkowski:true,canShoot:false};this.options={alwaysDoppler:false,neverDoppler:false,alwaysShowFramePos:false,neverShowFramePos:false,alwaysShowVisualPos:false,neverShowVisualPos:false,interactions:true};this.drawing=false;this.load=function(a,b){this.carray=[];this.curStep=b;this.demo=a;if(typeof a.steps[b].origin==="object")this.origin=a.steps[b].origin;this.timeScale=typeof a.steps[b].timeScale==="number"?
a.steps[b].timeScale:this.defaults.timeScale;if(typeof a.steps[b].zoom==="number")this.zoom=a.steps[b].zoom;this.curOptions=jQuery.extend({},this.defaults);typeof a.steps[b].options==="object"&&$.extend(this.curOptions,a.steps[b].options);c=this.curOptions.c?this.curOptions.c:1;drawLightCone(this,this.lCCtx);this.boost={left:boostFrom3Vel(-0.05*c,0,0),right:boostFrom3Vel(0.05*c,0,0),up:boostFrom3Vel(0,0.05*c,0),down:boostFrom3Vel(0,-0.05*c,0)};for(var d=0,d=0;d<a.steps[b].objects.length;d+=1)this.createObject(a.steps[b].objects[d]);
$("#caption").html(a.steps[b].caption);typeof a.steps[b].frame==="number"&&this.shiftToFrameOfObject(this.carray[a.steps[b].frame],a.steps[b].shift);this.frameStartTime=(new Date).getTime();this.loaded=true};this.pushCaption=function(a){$("#caption").html(a)};this.createObject=function(a){if(typeof a.options==="undefined")a.options={};if(typeof a.label==="undefined")a.label="";a.options=$.extend({},this.curOptions,a.options);a.x.length==2?a.x[2]=0:a.x.length==3&&(a.x[3]=0);a.p&&a.p.length==2&&(a.p[2]=
0);a=a.shape?new a.object(quat4.create([a.x[0],a.x[1],a.x[2],a.x[3]]),quat4.create([a.p[0],a.p[1],a.p[2],0]),a.label,a.options,a.shape):a.v?a.x[3]?new a.object(quat4.create([a.x[0],a.x[1],a.x[2],a.x[3]]),quat4.create([a.v[0],a.v[1],a.v[2],0]),a.label,a.options):new a.object(quat4.create([a.x[0],a.x[1],a.x[2],0]),quat4.create([a.v[0],a.v[1],a.v[2],0]),a.label,a.options):a.p?new a.object(quat4.create([a.x[0],a.x[1],a.x[2],a.x[3]]),quat4.create([a.p[0],a.p[1],a.p[2],0]),a.label,a.options):new a.object(quat4.create([a.x[0],
a.x[1],a.x[2],a.x[3]]),a.options);a.update(0,this);this.carray.push(a)};this.draw=function(){window.console&&window.console.firebug&&console.time("profile1");this.processInput();this.oldFrameStartTime=this.frameStartTime;this.frameStartTime=(new Date).getTime();var a=0;this.drawing&&(a=(this.frameStartTime-this.oldFrameStartTime)*this.timeScale*c);this.clear();this.curOptions.showText&&(this.h.beginPath(),this.h.fillText("t(s)",5+scene.origin[0],10),this.h.fillText("x(m)",scene.mWidth-30,scene.origin[2]-
10),this.h.fill());for(var b=0;b<this.carray.length;b++)this.carray[b].update(a,this),this.carray[b].draw(this);this.t+=a;(this.drawing||this.keyDown)&&requestAnimFrame(drawScene);window.console&&window.console.firebug&&console.timeEnd("profile1")};this.processInput=function(){if(fireDown&&this.curOptions.canShoot){for(var a=0,b,d=Infinity,e=new photon(quat4.create([0,0,0,0]),quat4.create([0,1,0,0]),"photon",{showCircle:false,fired:true,showFramePos:true}),f=0;f<this.carray.length;f++)if(this.carray[f].photonCollisionTime&&
(b=this.carray[f].photonCollisionTime(e),b<d&&(!this.carray[f].COM.endPt||this.carray[f].COM.endPt[3]>b)))d=b,a=f;if(d<Infinity)e.endPt=this.carray[a].photonCollision(e),this.carray[a].COM.endPt=quat4.create(e.endPt);this.carray.push(e);fireDown=false}leftDown===true&&this.changeArrayFrame(nullQuat4,this.boost.left);upDown===true&&this.changeArrayFrame(nullQuat4,this.boost.up);downDown===true&&this.changeArrayFrame(nullQuat4,this.boost.down);rightDown===true&&this.changeArrayFrame(nullQuat4,this.boost.right);
rotLeftDown===true&&this.changeArrayFrame(nullQuat4,rotRight);rotRightDown===true&&this.changeArrayFrame(nullQuat4,rotLeft);rotUpDown===true&&this.changeArrayFrame(nullQuat4,rotUp);rotDownDown===true&&this.changeArrayFrame(nullQuat4,rotDown);zoomOut==true&&zoomTo(scene.zoom*1.05);zoomIn==true&&zoomTo(scene.zoom/1.05);timeZoomIn==true&&(this.timeZoom/=1.05,drawLightCone(this,this.lCCtx));timeZoomOut==true&&(this.timeZoom*=1.05,drawLightCone(this,this.lCCtx));speedDown==true&&(this.timeScale/=1.1,updateSliders());
speedUp==true&&(this.timeScale*=1.1,updateSliders())};this.drawInfo=function(){scene.g.fillStyle="rgba(100,100,100,0.3)";scene.g.beginPath();scene.g.moveTo(10,10);scene.g.lineTo(150,10);scene.g.lineTo(150,110);scene.g.lineTo(10,110);scene.g.closePath();scene.g.fill();scene.g.fillStyle="rgba(150,0,150,1)";scene.g.fillText("Game Time: "+Math.round(this.t/c),30,30);scene.g.fillText("Real Time: "+Math.round((this.frameStartTime-this.initialTime)/c)/1E3,30,50);scene.g.fillText("Time speedup: "+Math.round(this.timeScale*
1E4)/10+"x",30,70);window.console&&window.console.firebug&&(scene.g.fillText("Fps: "+Math.round(1E3/(-this.oldFrameStartTime+this.frameStartTime)),30,80),scene.g.fillText("c: "+c,30,90),scene.g.fillText("keyCode: "+this.kC,30,100))};this.drawCrosshairs=function(){this.g.strokeStyle="#fff";this.g.beginPath();this.g.moveTo(this.origin[0]-10,this.origin[1]);this.g.lineTo(this.origin[0]+10,this.origin[1]);this.g.stroke();this.g.beginPath();this.g.moveTo(this.origin[0],this.origin[1]-10);this.g.lineTo(this.origin[0],
this.origin[1]+10);this.g.stroke()};this.clear=function(){this.g.clearRect(0,0,this.width,this.height);this.h.clearRect(0,0,this.mWidth,this.mHeight);this.TDC.clearRect(0,0,this.tWidth,this.tHeight)};this.startAnimation=function(){this.frameEndTime=(new Date).getTime();this.initialTime=(new Date).getTime();this.t=0;this.drawing||this.draw()};this.nextStep=function(){this.curStep+1<this.demo.steps.length&&(this.curStep+=1,this.replay())};this.prevStep=function(){this.curStep>0&&(this.curStep-=1,this.replay())};
this.replay=function(){this.load(this.demo,this.curStep);this.startAnimation()};this.pause=function(){this.drawing?this.drawing=false:(this.frameStartTime=(new Date).getTime(),this.drawing=true,this.draw())};this.findClosestObject=function(a,b,d){for(var e=this.width,f=-1,g=0;g<this.carray.length;g++)if(!this.carray[g].nonTimeLike){var h=this.carray[g].minDistanceTo([(a-this.origin[0])*this.zoom,-(b-this.origin[1])*this.zoom,0,0],this);h<e&&(e=h,f=g)}return e<d&&f>=0?this.carray[f]:false};this.shiftToFrameOfObject=
function(a,b){b?this.changeArrayFrame(quat4.create(a.getX0()),cBoostMat(a.getV(),c),b):this.changeArrayFrame(quat4.create(a.getX0()),cBoostMat(a.getV(),c))};this.changeArrayFrame=function(a,b,d){if(d)for(var e=0;e<this.carray.length;e++)this.carray[e].changeFrame(a,b,d);else for(e=0;e<this.carray.length;e++)this.carray[e].changeFrame(a,b)}}function drawScene(){scene.loaded&&scene.draw()}
function drawLightCone(a,b){var d=Math.max(a.origin[0],a.origin[2]),e=Math.min(d,d*c/a.zoom*a.timeZoom),d=e==d?d/c*a.zoom/a.timeZoom:d;b.fillStyle="#300";b.beginPath();b.moveTo(0,0);b.lineTo(0,d+a.origin[2]);b.lineTo(-e+a.origin[0],d+a.origin[2]);b.lineTo(e+a.origin[0],-d+a.origin[2]);b.lineTo(a.mWidth,-d+a.origin[2]);b.lineTo(a.mWidth,d+a.origin[2]);b.lineTo(e+a.origin[0],d+a.origin[2]);b.lineTo(-e+a.origin[0],-d+a.origin[2]);b.lineTo(-e+a.origin[0],-d+a.origin[2]);b.closePath();b.fill();b.fillStyle=
"#003";b.beginPath();b.moveTo(0,0);b.lineTo(a.mWidth,0);b.lineTo(e+a.origin[0],-d+a.origin[2]);b.lineTo(-e+a.origin[0],d+a.origin[2]);b.lineTo(-e+a.origin[0],a.mHeight);b.lineTo(e+a.origin[0],a.mHeight);b.lineTo(e+a.origin[0],d+a.origin[2]);b.lineTo(-e+a.origin[0],-d+a.origin[2]);b.closePath();b.fill();b.strokeStyle="#FFF";b.lineWidth=3;b.beginPath();b.moveTo(0,a.origin[2]);b.lineTo(a.mWidth,a.origin[2]);b.moveTo(a.origin[0],0);b.lineTo(a.origin[0],a.mHeight);b.stroke();b.lineWidth=1;b.fillStyle=
"#fff"}function setSize(a){a.width=$("#canvas").width();a.height=$("#canvas").height();a.mWidth=$("#minkowski").width();a.mHeight=$("#minkowski").height();a.tWidth=$("#3DCanvas").width();a.tHeight=$("#3DCanvas").height();a.lightConeCanvas.width=a.mWidth;a.lightConeCanvas.height=a.mHeight;a.hwidth=a.width/2;a.hheight=a.height/2;a.origin=[a.hwidth,a.hheight,a.hheight];drawLightCone(a,a.lCCtx)};
